# Generated by Django 5.2.1 on 2025-06-12 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cars/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('HTB', 'Hatchback'), ('SD', 'Sedan'), ('SUV', 'SUV'), ('MUV', 'MUV'), ('LX', 'Luxury')], max_length=3)),
            ],
        ),
    ]
